## YAML Template.
---
name: Java Maven Docker Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR using Maven
        run: mvn clean package

      - name: Build Docker Image
        run: docker build -t labtask11 .

      - name: Stop Old Container
        run: docker rm -f labtask11-container || true

      - name: Run New Container
        run: |
          docker run -d \
          --name labtask11-container \
          -p 8080:8080 \
          labtask11